apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: senthil123/nodejs-app:latest
          ports:
            - containerPort: 3000  # Adjust based on your app's listening port
          readinessProbe:
            httpGet:
              path: /health  # Change this path as per your app
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 3000         # Port that the service will expose
      targetPort: 3000   # Port on the container
      nodePort: 30005    # NodePort (optional, Kubernetes will assign one if not specified)
